import assert from 'node:assert/strict';
import worker, { canDeleteComment, canView,normalizeAuthUser,validPart } from './src/index';
assert.equal(canView({ visibility:'public', revoked:0, owner_id:'a' }),true); assert.equal(canView({visibility:'private',revoked:0,owner_id:'a'},'b',false),false); assert.equal(canView({visibility:'private',revoked:0,owner_id:'a'},'b',true),true); assert.equal(canView({visibility:'public',revoked:1,owner_id:'a'}),false);
assert.equal(canDeleteComment({owner_id:'owner'},{author_id:'author'},'author'),true); assert.equal(canDeleteComment({owner_id:'owner'},{author_id:'author'},'other'),false);
assert.equal(canView({visibility:'private',revoked:0,owner_id:'owner'},'owner',false),true);assert.equal(canView({visibility:'private',revoked:0,owner_id:'owner'},null,false),false);assert.equal(canView({visibility:'public',revoked:0,owner_id:'owner',expires_at:new Date(Date.now()-1).toISOString()}),false);assert.equal(validPart(1,8*1024*1024),true);assert.equal(validPart(0,10),false);assert.equal(validPart(1,9*1024*1024),false);
assert.deepEqual(normalizeAuthUser({session:{userId:'topoo-user-1',displayName:'Topoo User',email:'user@topoo.ai'}}),{id:'topoo-user-1',userId:'topoo-user-1',displayName:'Topoo User',email:'user@topoo.ai'});assert.equal(normalizeAuthUser({session:{displayName:'Missing ID'}}),null);
const response=await worker.fetch(new Request('https://share.topoo.ai/health'),{} as any); assert.equal(response.status,200); assert.deepEqual(await response.json(),{ok:true});
const viewer=await worker.fetch(new Request('https://share.topoo.ai/s/demo'),{} as any);const html=await viewer.text();assert.match(viewer.headers.get('content-security-policy')??'',/connect-src 'self' https:\/\/auth\.topoo\.ai/);assert.match(html,/replaceChildren/);assert.match(html,/github\/start\?entranceType=desktop&responseMode=json/);assert.match(html,/sessionStorage\.setItem\('topooShareToken'/);assert.match(html,/window\.open\('about:blank'/);assert.match(html,/popup\.location\.href=start\.authorizeUrl/);assert.ok(html.indexOf("window.open('about:blank'")<html.indexOf("await fetch('https://auth.topoo.ai/api/auth/github/start"));assert.match(html,/if\(!popup\).*Allow pop-ups/s);assert.match(html,/catch\(error\)\{popup\.close\(\);alert\('Topoo sign-in failed:/);assert.doesNotMatch(html,/comments\.innerHTML/);
console.log(JSON.stringify({status:'ok',worker:true,policies:['public','unlisted','private','revoked','comment-owner']}));
