import type { PresentationEffectRegion } from './types';
import { Button } from '@/components/ui/button';
import { Switch } from '@/components/ui/switch';

interface Props { effect: PresentationEffectRegion; playheadMs: number; onChange: (patch: Partial<PresentationEffectRegion>) => void; onDelete: () => void }
const Field = ({ label, children }: { label: string; children: React.ReactNode }) => <label className="block space-y-1.5"><span className="text-[11px] text-[var(--ui-text-secondary)]">{label}</span>{children}</label>;
const Input = (props: React.InputHTMLAttributes<HTMLInputElement>) => <input {...props} className="h-8 w-full rounded-[5px] border-0 bg-[var(--ui-control)] px-2 text-[12px] text-[var(--ui-text-primary)]" />;
export function PresentationSettingsPanel({ effect, playheadMs, onChange, onDelete }: Props) {
  return <section className="space-y-3 px-4 py-3">
    <div className="text-[12px] font-semibold capitalize text-[var(--ui-text-primary)]">{effect.kind.replace('-', ' ')}</div>
    {effect.kind === 'cursor-visibility' && <Field label="Cursor visible"><Switch checked={effect.visible} onCheckedChange={(visible) => onChange({ visible } as Partial<PresentationEffectRegion>)} /></Field>}
    {effect.kind === 'mask' && <><Field label="Mode"><select value={effect.mode} onChange={e => onChange({ mode: e.target.value } as Partial<PresentationEffectRegion>)} className="h-8 w-full rounded bg-[var(--ui-control)] px-2 text-xs"><option value="blur">Blur</option><option value="cover">Cover</option></select></Field><Field label="Blur"><Input type="range" min={2} max={48} value={effect.blurPx} onChange={e => onChange({ blurPx: Number(e.target.value) } as Partial<PresentationEffectRegion>)} /></Field><Field label="Color"><Input type="color" value={effect.color} onChange={e => onChange({ color: e.target.value } as Partial<PresentationEffectRegion>)} /></Field><Field label="Opacity"><Input type="range" min={0} max={1} step={.05} value={effect.opacity} onChange={e => onChange({ opacity: Number(e.target.value) } as Partial<PresentationEffectRegion>)} /></Field><Field label="Follow"><select value={effect.follow} onChange={e => onChange({ follow: e.target.value } as Partial<PresentationEffectRegion>)} className="h-8 w-full rounded bg-[var(--ui-control)] px-2 text-xs"><option value="fixed">Fixed</option><option value="keyframes">Key positions</option></select></Field><Button className="w-full" variant="outline" onClick={() => onChange({ follow: 'keyframes', followKeyframes: [...effect.followKeyframes, { timeMs: playheadMs, x: effect.bounds.x, y: effect.bounds.y }] } as Partial<PresentationEffectRegion>)}>Add current position</Button></>}
    {effect.kind === 'highlight' && <><Field label="Highlight color"><Input type="color" value={effect.color} onChange={e => onChange({ color: e.target.value } as Partial<PresentationEffectRegion>)} /></Field><Field label="Dim"><Input type="range" min={0} max={.85} step={.05} value={effect.dimOpacity} onChange={e => onChange({ dimOpacity: Number(e.target.value) } as Partial<PresentationEffectRegion>)} /></Field><Field label="Opacity"><Input type="range" min={0} max={1} step={.05} value={effect.opacity} onChange={e => onChange({ opacity: Number(e.target.value) } as Partial<PresentationEffectRegion>)} /></Field></>}
    {effect.kind === 'click-effect' && <><Field label="Style"><select value={effect.style} onChange={e => onChange({ style: e.target.value } as Partial<PresentationEffectRegion>)} className="h-8 w-full rounded bg-[var(--ui-control)] px-2 text-xs"><option value="ripple">Ripple</option><option value="shockwave">Shockwave</option><option value="pulse">Pulse</option></select></Field><Field label="Size"><Input type="range" min={.5} max={3} step={.1} value={effect.size} onChange={e => onChange({ size: Number(e.target.value) } as Partial<PresentationEffectRegion>)} /></Field><Field label="Intensity"><Input type="range" min={.1} max={2} step={.1} value={effect.intensity} onChange={e => onChange({ intensity: Number(e.target.value) } as Partial<PresentationEffectRegion>)} /></Field><Field label="Click sound"><Switch checked={effect.soundEnabled} onCheckedChange={soundEnabled => onChange({ soundEnabled } as Partial<PresentationEffectRegion>)} /></Field><Field label="Sound volume"><Input type="range" min={0} max={1} step={.05} value={effect.soundVolume} onChange={e => onChange({ soundVolume: Number(e.target.value) } as Partial<PresentationEffectRegion>)} /></Field></>}
    {effect.kind === 'keystroke' && <><Field label="Keys"><Input value={effect.keys.join('+')} onChange={e => onChange({ keys: e.target.value.split('+').map(key => key.trim()).filter(Boolean) } as Partial<PresentationEffectRegion>)} /></Field><Field label="Position"><select value={effect.placement} onChange={e => onChange({ placement: e.target.value } as Partial<PresentationEffectRegion>)} className="h-8 w-full rounded bg-[var(--ui-control)] px-2 text-xs"><option value="bottom">Bottom</option><option value="center">Center</option><option value="top-left">Top left</option><option value="top-right">Top right</option></select></Field><Field label="Style"><select value={effect.style} onChange={e => onChange({ style: e.target.value } as Partial<PresentationEffectRegion>)} className="h-8 w-full rounded bg-[var(--ui-control)] px-2 text-xs"><option value="dark">Dark</option><option value="light">Light</option><option value="accent">Accent</option></select></Field><Field label="Display duration (ms)"><Input type="number" min={100} value={effect.durationMs} onChange={e => onChange({ durationMs: Number(e.target.value), endMs: effect.startMs + Number(e.target.value) } as Partial<PresentationEffectRegion>)} /></Field></>}
    {effect.kind === 'presenter' && <><Field label="Visible"><Switch checked={effect.visible} onCheckedChange={visible => onChange({ visible } as Partial<PresentationEffectRegion>)} /></Field><Field label="Opacity"><Input type="range" min={0} max={1} step={.05} value={effect.opacity ?? 1} onChange={e => onChange({ opacity: Number(e.target.value) } as Partial<PresentationEffectRegion>)} /></Field><Field label="Shape"><select value={effect.shape} onChange={e => onChange({ shape: e.target.value } as Partial<PresentationEffectRegion>)} className="h-8 w-full rounded bg-[var(--ui-control)] px-2 text-xs"><option value="circle">Circle</option><option value="rectangle">Rectangle</option></select></Field><Field label="Fit"><select value={effect.fit} onChange={e => onChange({ fit: e.target.value } as Partial<PresentationEffectRegion>)} className="h-8 w-full rounded bg-[var(--ui-control)] px-2 text-xs"><option value="cover">Cover</option><option value="contain">Contain</option></select></Field><div className="rounded bg-[var(--ui-control)] px-2 py-2 text-[11px] text-[var(--ui-text-secondary)]">{effect.sourceUrl ? 'Recording camera asset connected' : effect.posterDataUrl ? 'Camera poster only — video asset missing' : 'Camera asset missing — record with camera enabled'}</div></>}
    <Button variant="destructive" className="w-full" onClick={onDelete}>Delete region</Button>
  </section>;
}
