export interface Env { DB: any; MEDIA: any; AUTH_SESSION_URL: string; PUBLIC_BASE_URL: string; PLAYBACK_SIGNING_SECRET: string }
type User = { id: string; displayName?: string; nickname?: string; email?: string; avatarUrl?: string; avatar_url?: string };
const json = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { 'content-type': 'application/json', 'access-control-allow-origin': '*' } });
const id = () => crypto.randomUUID(); const now = () => new Date().toISOString();
export function normalizeAuthUser(raw:any):User|null{const value=raw?.user??raw?.session??raw;const userId=value?.id??value?.userId;return userId?{...value,id:userId}:null;}
async function user(request: Request, env: Env, required = true): Promise<User | null> { const authorization = request.headers.get('authorization'); const cookie = request.headers.get('cookie'); if (!authorization && !cookie) { if (required) throw new Response('Unauthorized', { status: 401 }); return null; } const headers: Record<string,string> = {}; if (authorization) headers.authorization=authorization; if(cookie) headers.cookie=cookie; const response = await fetch(env.AUTH_SESSION_URL, { headers }); if (!response.ok) throw new Response('Unauthorized', { status: 401 }); const value=normalizeAuthUser(await response.json());if(!value)throw new Response('Unauthorized',{status:401});return value; }
export function canView(share: any, viewerId?: string | null, member = false) { if (!share || share.revoked || (share.expires_at && Date.parse(share.expires_at) <= Date.now())) return false; return share.visibility !== 'private' || viewerId === share.owner_id || member; }
export function canDeleteComment(share: any, comment: any, viewerId?: string | null) { return Boolean(viewerId && (viewerId === share.owner_id || viewerId === comment.author_id)); }
export function validPart(partNumber:number,length:number){return Number.isInteger(partNumber)&&partNumber>=1&&partNumber<=10000&&Number.isInteger(length)&&length>0&&length<=8*1024*1024;}
async function signature(key: string, exp: number, secret: string) { const bytes = new TextEncoder().encode(secret); const cryptoKey = await crypto.subtle.importKey('raw', bytes, { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']); const signed = await crypto.subtle.sign('HMAC', cryptoKey, new TextEncoder().encode(`${key}:${exp}`)); return [...new Uint8Array(signed)].map(x => x.toString(16).padStart(2, '0')).join(''); }
async function getShare(env: Env, slug: string) { return env.DB.prepare('SELECT s.*,u.storage_key,u.content_type,u.byte_size FROM shares s JOIN uploads u ON u.id=s.upload_id WHERE s.slug=?').bind(slug).first(); }
async function authorizedShare(request: Request, env: Env, slug: string) { const share = await getShare(env, slug); const viewer = await user(request, env, false); const member = viewer && share ? await env.DB.prepare('SELECT 1 FROM share_members WHERE share_id=? AND user_id=?').bind(share.id, viewer.id).first() : null; if (!canView(share, viewer?.id, Boolean(member))) throw new Response('Forbidden', { status: share ? 403 : 404 }); return { share, viewer }; }

export default { async fetch(request: Request, env: Env): Promise<Response> {
  try {
    if (request.method === 'OPTIONS') return new Response(null, { headers: { 'access-control-allow-origin': '*', 'access-control-allow-headers': 'authorization,content-type', 'access-control-allow-methods': 'GET,POST,PUT,PATCH,DELETE' } });
    const url = new URL(request.url); const segments = url.pathname.split('/').filter(Boolean);
    if (url.pathname === '/health') return json({ ok: true });
    if (segments[0] === 's' && request.method === 'GET') return new Response(`<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>ToScreen Share</title><style>body{margin:0;background:#0b0c0f;color:#fff;font:14px system-ui}.wrap{max-width:960px;margin:40px auto;padding:20px}video{width:100%;background:#000;border-radius:12px}.meta{color:#9ca3af}.comment{padding:10px 0;border-bottom:1px solid #252832}input,button{padding:10px;border-radius:7px;border:1px solid #333;background:#17191e;color:#fff}</style><div class="wrap"><h1 id="title">Loading…</h1><div class="meta" id="meta"></div><video id="video" controls></video><h2>Comments</h2><form id="form"><input id="body" required maxlength="2000" placeholder="Comment at current time"><button>Post</button></form><div id="comments"></div></div><script>const slug=${JSON.stringify(segments[1] ?? '')};const headers={};async function load(){const r=await fetch('/v1/shares/'+slug,{headers,credentials:'include'});if(!r.ok){document.getElementById('title').textContent=r.status===403?'Private share — open from an authorized Topoo session':'Share unavailable';return}const s=await r.json();title.textContent=s.title;meta.textContent='Owner '+s.ownerId+' · '+new Date(s.createdAt).toLocaleString()+' · '+s.visibility;video.src=s.playbackUrl;const c=await fetch('/v1/shares/'+slug+'/comments',{headers,credentials:'include'});if(c.ok){const data=await c.json();comments.replaceChildren(...data.items.map(x=>{const d=document.createElement('div');d.className='comment';const b=document.createElement('b');b.textContent=x.author_name;d.append(b,document.createTextNode(' at '+Math.round(x.timestamp_ms/1000)+'s'),document.createElement('br'),document.createTextNode(x.body));return d}))}}form.onsubmit=async e=>{e.preventDefault();const r=await fetch('/v1/shares/'+slug+'/comments',{method:'POST',credentials:'include',headers:{...headers,'content-type':'application/json'},body:JSON.stringify({timestampMs:video.currentTime*1000,body:body.value})});if(r.status===401){alert('Sign in through Topoo Account to comment.');return}body.value='';load()};load()</script>`, { headers: { 'content-type': 'text/html;charset=utf-8','content-security-policy':"default-src 'self'; media-src 'self'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'",'x-content-type-options':'nosniff','referrer-policy':'no-referrer' } });
    if (segments[0] === 'media' && request.method === 'GET') { const slug = segments[1]; const share = await getShare(env, slug); const exp = Number(url.searchParams.get('exp')); const sig = url.searchParams.get('sig'); if (!share || exp < Date.now() || sig !== await signature(share.storage_key, exp, env.PLAYBACK_SIGNING_SECRET)) return new Response('Forbidden', { status: 403 }); const object = await env.MEDIA.get(share.storage_key); return object ? new Response(object.body, { headers: { 'content-type': share.content_type } }) : new Response('Not found', { status: 404 }); }
    if (url.pathname === '/v1/uploads' && request.method === 'POST') { const owner = await user(request, env) as User; const body: any = await request.json(); if (!Number.isSafeInteger(body.size)||body.size<=0||body.size>20*1024*1024*1024||!/^[a-f0-9]{64}$/.test(body.checksum)||!['video/mp4','image/gif'].includes(body.contentType)) return json({ error: 'Invalid upload' }, 400); const uploadId = id(), storageKey = `uploads/${owner.id}/${uploadId}`; const multipart=await env.MEDIA.createMultipartUpload(storageKey,{httpMetadata:{contentType:body.contentType},customMetadata:{checksum:body.checksum}}); await env.DB.prepare('INSERT INTO uploads VALUES(?,?,?,?,?,?,?,?,?,?)').bind(uploadId, owner.id, 'uploading', body.size, body.checksum, body.contentType, storageKey, multipart.uploadId, now(), new Date(Date.now() + 86400000).toISOString()).run(); return json({ id: uploadId, partSize: 8*1024*1024, completedParts: [] }, 201); }
    if (segments[0] === 'v1' && segments[1] === 'uploads' && segments.length===3 && request.method==='GET'){const owner=await user(request,env) as User;const upload=await env.DB.prepare('SELECT * FROM uploads WHERE id=? AND owner_id=?').bind(segments[2],owner.id).first();if(!upload)return json({error:'Not found'},404);const parts=(await env.DB.prepare('SELECT part_number as partNumber,etag,byte_size as size FROM upload_parts WHERE upload_id=? ORDER BY part_number').bind(upload.id).all()).results;return json({id:upload.id,state:upload.state,partSize:8*1024*1024,completedParts:parts});}
    if (segments[0] === 'v1' && segments[1] === 'uploads' && segments[3] === 'parts' && request.method === 'PUT') { const owner = await user(request, env) as User; const upload = await env.DB.prepare('SELECT * FROM uploads WHERE id=? AND owner_id=? AND state=?').bind(segments[2], owner.id, 'uploading').first(); if (!upload) return json({ error: 'Not found' }, 404); const partNumber=Number(segments[4]);const length=Number(request.headers.get('content-length'));if(!validPart(partNumber,length))return json({error:'Invalid part'},400);const multipart=env.MEDIA.resumeMultipartUpload(upload.storage_key,upload.multipart_upload_id);const part=await multipart.uploadPart(partNumber,request.body);await env.DB.prepare('INSERT INTO upload_parts VALUES(?,?,?,?) ON CONFLICT(upload_id,part_number) DO UPDATE SET etag=excluded.etag,byte_size=excluded.byte_size').bind(upload.id,partNumber,part.etag,length).run();return json({partNumber,etag:part.etag,size:length}); }
    if (segments[0] === 'v1' && segments[1] === 'uploads' && segments[3] === 'finalize' && request.method === 'POST') { const owner = await user(request, env) as User; const upload = await env.DB.prepare('SELECT * FROM uploads WHERE id=? AND owner_id=? AND state=?').bind(segments[2], owner.id,'uploading').first(); if (!upload) return json({ error: 'Not found' }, 404); const parts=(await env.DB.prepare('SELECT part_number,etag,byte_size FROM upload_parts WHERE upload_id=? ORDER BY part_number').bind(upload.id).all()).results;if(!parts.length||parts.reduce((sum:number,p:any)=>sum+p.byte_size,0)!==upload.byte_size||parts.some((p:any,i:number)=>p.part_number!==i+1))return json({error:'Incomplete upload'},409);const multipart=env.MEDIA.resumeMultipartUpload(upload.storage_key,upload.multipart_upload_id);const object=await multipart.complete(parts.map((p:any)=>({partNumber:p.part_number,etag:p.etag})));if(object.size!==upload.byte_size)return json({error:'Completed size mismatch'},409);await env.DB.prepare('UPDATE uploads SET state=? WHERE id=?').bind('sealed',upload.id).run();return json({ sealed: true,checksum:upload.checksum }); }
    if (segments[0]==='v1'&&segments[1]==='uploads'&&segments.length===3&&request.method==='DELETE'){const owner=await user(request,env) as User;const upload=await env.DB.prepare('SELECT * FROM uploads WHERE id=? AND owner_id=? AND state=?').bind(segments[2],owner.id,'uploading').first();if(!upload)return json({error:'Not found'},404);await env.MEDIA.resumeMultipartUpload(upload.storage_key,upload.multipart_upload_id).abort();await env.DB.prepare('UPDATE uploads SET state=? WHERE id=?').bind('aborted',upload.id).run();await env.DB.prepare('DELETE FROM upload_parts WHERE upload_id=?').bind(upload.id).run();return json({aborted:true});}
    if (url.pathname === '/v1/shares' && request.method === 'POST') { const owner = await user(request, env) as User; const body:any=await request.json(); const upload=await env.DB.prepare('SELECT * FROM uploads WHERE id=? AND owner_id=? AND state=?').bind(body.uploadId,owner.id,'sealed').first(); if(!upload)return json({error:'Upload not sealed'},409); const expiry=body.expiresAt?Date.parse(body.expiresAt):null;if(!['public','unlisted','private'].includes(body.visibility)||typeof body.title!=='string'||body.title.length<1||body.title.length>200||(expiry!==null&&(!Number.isFinite(expiry)||expiry<=Date.now())))return json({error:'Invalid share'},400); const shareId=id(),slug=crypto.randomUUID().replaceAll('-','').slice(0,16),timestamp=now(); await env.DB.prepare('INSERT INTO shares VALUES(?,?,?,?,?,?,?,?,?,?)').bind(shareId,owner.id,upload.id,body.title,slug,body.visibility,0,expiry?new Date(expiry).toISOString():null,timestamp,timestamp).run(); return json({slug,url:`${env.PUBLIC_BASE_URL}/s/${slug}`},201); }
    if (url.pathname === '/v1/shares' && request.method === 'GET') { const owner=await user(request,env) as User; return json({items:(await env.DB.prepare('SELECT * FROM shares WHERE owner_id=? ORDER BY created_at DESC').bind(owner.id).all()).results}); }
    if (segments[0]==='v1'&&segments[1]==='shares'&&segments.length===3&&request.method==='GET'){const {share,viewer}=await authorizedShare(request,env,segments[2]);const exp=Date.now()+300000;const sig=await signature(share.storage_key,exp,env.PLAYBACK_SIGNING_SECRET);return json({slug:share.slug,title:share.title,visibility:share.visibility,ownerId:share.owner_id,createdAt:share.created_at,viewerId:viewer?.id,playbackUrl:`${env.PUBLIC_BASE_URL}/media/${share.slug}?exp=${exp}&sig=${sig}`});}
    if (segments[0]==='v1'&&segments[1]==='shares'&&segments.length===3&&request.method==='PATCH'){const owner=await user(request,env) as User;const body:any=await request.json();const share=await getShare(env,segments[2]);if(!share||share.owner_id!==owner.id)return json({error:'Forbidden'},403);const expiry=body.expiresAt===null?null:body.expiresAt?Date.parse(body.expiresAt):undefined;if((body.title!==undefined&&(typeof body.title!=='string'||body.title.length<1||body.title.length>200))||(body.visibility!==undefined&&!['public','unlisted','private'].includes(body.visibility))||(body.revoked!==undefined&&typeof body.revoked!=='boolean')||(expiry!==undefined&&expiry!==null&&(!Number.isFinite(expiry)||expiry<=Date.now())))return json({error:'Invalid patch'},400);await env.DB.prepare('UPDATE shares SET title=?,visibility=?,revoked=?,expires_at=?,updated_at=? WHERE id=?').bind(body.title??share.title,body.visibility??share.visibility,body.revoked===undefined?share.revoked:Number(body.revoked),expiry===undefined?share.expires_at:expiry===null?null:new Date(expiry).toISOString(),now(),share.id).run();return json({ok:true});}
    if (segments[0]==='v1'&&segments[1]==='shares'&&segments[3]==='comments') { const slug=segments[2]; const {share,viewer}=await authorizedShare(request,env,slug); if(segments.length===4&&request.method==='GET')return json({items:(await env.DB.prepare('SELECT * FROM share_comments WHERE share_id=? ORDER BY timestamp_ms').bind(share.id).all()).results}); if(segments.length===4&&request.method==='POST'){const author=viewer??await user(request,env) as User;const body:any=await request.json();if(typeof body.body!=='string'||body.body.trim().length<1||body.body.length>2000||!Number.isSafeInteger(body.timestampMs)||body.timestampMs<0||body.timestampMs>24*60*60*1000)return json({error:'Invalid comment'},400);const commentId=id(),timestamp=now();await env.DB.prepare('INSERT INTO share_comments VALUES(?,?,?,?,?,?,?,?,?)').bind(commentId,share.id,author.id,author.displayName??author.nickname??author.email??'Topoo user',body.timestampMs,body.body.trim(),0,timestamp,timestamp).run();return json({id:commentId},201);} const comment=await env.DB.prepare('SELECT * FROM share_comments WHERE id=? AND share_id=?').bind(segments[4],share.id).first();if(!comment)return json({error:'Not found'},404);if(request.method==='PATCH'){if(viewer?.id!==share.owner_id)return json({error:'Forbidden'},403);const body:any=await request.json();if(typeof body.resolved!=='boolean')return json({error:'Invalid comment patch'},400);await env.DB.prepare('UPDATE share_comments SET resolved=?,updated_at=? WHERE id=?').bind(Number(body.resolved),now(),comment.id).run();return json({ok:true});}if(request.method==='DELETE'){if(!canDeleteComment(share,comment,viewer?.id))return json({error:'Forbidden'},403);await env.DB.prepare('DELETE FROM share_comments WHERE id=?').bind(comment.id).run();return json({ok:true});}}
    return json({ error: 'Not found' }, 404);
  } catch (error) { if (error instanceof Response) return error; return json({ error: String(error) }, 500); }
} };
