import { useEffect, useMemo, useRef, useState } from 'react'
import type { AudioRegion } from './types'
import { bundledMusicToAudioRegion, mergeSubtitles, splitSubtitle, transcriptToSubtitles, type SubtitleRegion } from './mediaFeatures'

type Track = { id: string; title: string; file: string; category: string; durationSeconds: number; source: string; license: string }
export function MediaFeaturesPanel({ currentTimeMs, audioRegions, onAddAudio, subtitles, onChangeSubtitles }: { currentTimeMs: number; audioRegions: AudioRegion[]; onAddAudio: (region: AudioRegion) => void; subtitles: SubtitleRegion[]; onChangeSubtitles: (regions: SubtitleRegion[]) => void }) {
  const [tracks, setTracks] = useState<Track[]>([]), [query, setQuery] = useState(''), [category, setCategory] = useState('All')
  const [language, setLanguage] = useState('en-US'), [source, setSource] = useState<'system'|'microphone'|'mix'>('microphone'), [progress, setProgress] = useState(0), [error, setError] = useState('')
  const preview = useRef<HTMLAudioElement | null>(null)
  useEffect(() => { void window.electronAPI.listBundledMusic().then(result => result.success && result.manifest ? setTracks(result.manifest.tracks) : setError(result.error || 'Bundled music is unavailable')) }, [])
  const resolveMusic = async (track: Track) => {
    const result = await window.electronAPI.resolveBundledMusic(track.file)
    if (!result.success || !result.url) throw new Error(result.error || 'Bundled music is unavailable')
    return result.url
  }
  useEffect(() => window.electronAPI.onTranscriptionProgress((event: any) => { if (event?.type === 'progress') setProgress(event.value) }), [])
  const visible = useMemo(() => tracks.filter(track => (category === 'All' || track.category === category) && `${track.title} ${track.category}`.toLowerCase().includes(query.toLowerCase())), [tracks, query, category])
  const transcribe = async () => {
    setError(''); setProgress(5)
    const candidates = audioRegions.filter(region => source === 'mix' ? ['system-audio','microphone'].includes(region.role || '') : region.role === `${source}-audio` || region.role === source)
    const paths = candidates.filter(region => !region.isMuted && region.volume > 0 && region.path).map(region => region.path!)
    if (!paths.length) { setError('Selected source is muted, unavailable, or has no local file.'); setProgress(0); return }
    try { const result = await window.electronAPI.transcribeAudio({ paths, language }); if (result.success && result.segments) onChangeSubtitles(transcriptToSubtitles(result.segments, subtitles)); else setError(result.error || 'Transcription failed'); setProgress(result.success ? 100 : 0) }
    catch (cause) { setError(cause instanceof Error ? cause.message : 'Transcription failed'); setProgress(0) }
  }
  return <aside className="w-80 border-l border-zinc-800 bg-zinc-950 p-3 overflow-auto text-xs text-zinc-200">
    <h3 className="font-semibold mb-2">Built-in music</h3><div className="flex gap-2 mb-2"><input className="bg-zinc-900 p-2 rounded w-full" placeholder="Search" value={query} onChange={e=>setQuery(e.target.value)} /><select className="bg-zinc-900 rounded" value={category} onChange={e=>setCategory(e.target.value)}><option>All</option><option>Ambient</option><option>Upbeat</option></select></div>
    {visible.map(track => <div key={track.id} className="border border-zinc-800 rounded p-2 mb-2"><b>{track.title}</b><div className="text-zinc-500">{track.category} · {track.license} · {track.source}</div><div className="flex gap-2 mt-1"><button onClick={()=>void resolveMusic(track).then(url=>{ preview.current?.pause(); preview.current=new Audio(url); return preview.current.play() }).catch(cause=>setError(String(cause)))}>Preview</button><button onClick={()=>void resolveMusic(track).then(url=>onAddAudio(bundledMusicToAudioRegion(track,currentTimeMs,url))).catch(cause=>setError(String(cause)))}>Add to Audio Track</button></div></div>)}
    <h3 className="font-semibold mt-4 mb-2">Local transcription</h3><div className="flex gap-2"><select className="bg-zinc-900 p-2" value={language} onChange={e=>setLanguage(e.target.value)}><option value="en-US">English</option><option value="zh-CN">简体中文</option><option value="zh-TW">繁體中文</option><option value="ja-JP">日本語</option></select><select className="bg-zinc-900 p-2" value={source} onChange={e=>setSource(e.target.value as any)}><option value="microphone">Microphone</option><option value="system">System</option><option value="mix">Mix</option></select></div><div className="flex gap-2 my-2"><button onClick={()=>void transcribe()}>Transcribe</button><button onClick={()=>void window.electronAPI.cancelTranscription()}>Cancel</button><span>{progress}%</span></div>{error&&<p className="text-red-400">{error}</p>}
    <h3 className="font-semibold mt-4 mb-2">Subtitles</h3>{subtitles.map((subtitle,index)=>{ const updateStyle=(patch:Partial<SubtitleRegion['style']>)=>onChangeSubtitles(subtitles.map(item=>item.id===subtitle.id?{...item,style:{...item.style,...patch},userEdited:true}:item)); return <div key={subtitle.id} className="border border-zinc-800 rounded p-2 mb-2"><textarea className="w-full bg-zinc-900" value={subtitle.text} onChange={e=>onChangeSubtitles(subtitles.map(item=>item.id===subtitle.id?{...item,text:e.target.value,userEdited:true}:item))}/><div className="flex gap-1"><input type="number" value={subtitle.startMs} onChange={e=>onChangeSubtitles(subtitles.map(item=>item.id===subtitle.id?{...item,startMs:+e.target.value,userEdited:true}:item))}/><input type="number" value={subtitle.endMs} onChange={e=>onChangeSubtitles(subtitles.map(item=>item.id===subtitle.id?{...item,endMs:+e.target.value,userEdited:true}:item))}/></div><div className="grid grid-cols-3 gap-1 my-1"><select value={subtitle.style.fontFamily} onChange={e=>updateStyle({fontFamily:e.target.value})}><option>Geist Sans</option><option>Arial</option><option>Georgia</option></select><input type="number" min="12" max="96" value={subtitle.style.fontSize} onChange={e=>updateStyle({fontSize:+e.target.value})}/><input type="color" value={subtitle.style.color} onChange={e=>updateStyle({color:e.target.value})}/><input type="color" value={subtitle.style.backgroundColor.slice(0,7)} onChange={e=>updateStyle({backgroundColor:e.target.value+'99'})}/><select value={subtitle.style.position} onChange={e=>updateStyle({position:e.target.value as any})}><option>top</option><option>center</option><option>bottom</option></select><select value={subtitle.style.align} onChange={e=>updateStyle({align:e.target.value as any})}><option>left</option><option>center</option><option>right</option></select></div><div className="flex gap-2"><button onClick={()=>onChangeSubtitles(subtitles.flatMap(item=>item.id===subtitle.id?splitSubtitle(item,(item.startMs+item.endMs)/2):[item]))}>Split</button>{index<subtitles.length-1&&<button onClick={()=>onChangeSubtitles([...subtitles.slice(0,index),mergeSubtitles(subtitle,subtitles[index+1]),...subtitles.slice(index+2)])}>Merge next</button>}<button onClick={()=>onChangeSubtitles(subtitles.filter(item=>item.id!==subtitle.id))}>Delete</button><select value={subtitle.style.animation} onChange={e=>updateStyle({animation:e.target.value as any})}><option>none</option><option>fade</option><option>pop</option></select></div></div>})}
  </aside>
}
