import {useCallback,useEffect,useState} from 'react';
import {Button} from '../ui/button';

type Share={id:string;slug:string;title:string;visibility:'public'|'unlisted'|'private';revoked:number;expires_at?:string|null};
type Comment={id:string;author_name:string;body:string;timestamp_ms:number;resolved:number};
const serviceUrl=import.meta.env.VITE_TOPOO_SHARE_URL||'https://share.topoo.ai';

export function ShareHistoryDialog({onClose}:{onClose:()=>void}){
  const[items,setItems]=useState<Share[]>([]);const[selected,setSelected]=useState<Share|null>(null);const[comments,setComments]=useState<Comment[]>([]);const[error,setError]=useState('');
  const load=useCallback(async()=>{try{const value=await window.electronAPI.shareApi(serviceUrl,'GET','/v1/shares');setItems(value.items??[]);setError('');}catch(value){setError(String(value));}},[]);
  useEffect(()=>{void load();},[load]);
  const patch=async(share:Share,body:unknown)=>{await window.electronAPI.shareApi(serviceUrl,'PATCH',`/v1/shares/${share.slug}`,body);await load();};
  const loadComments=async(share:Share)=>{setSelected(share);const value=await window.electronAPI.shareApi(serviceUrl,'GET',`/v1/shares/${share.slug}/comments`);setComments(value.items??[]);};
  return <div className="fixed inset-0 z-[120] grid place-items-center bg-black/50" onMouseDown={event=>{if(event.target===event.currentTarget)onClose();}}><div className="max-h-[75vh] w-[620px] max-w-[92vw] overflow-auto rounded-lg border border-[var(--ui-border)] bg-[var(--ui-inspector-surface)] p-4 text-[10px]"><div className="mb-3 flex items-center justify-between"><strong className="text-[12px]">Topoo shares</strong><Button variant="outline" className="h-7" onClick={onClose}>Close</Button></div>{error&&<div className="mb-2 text-red-500">{error}</div>}{items.length===0&&!error&&<div className="text-[var(--ui-text-tertiary)]">No shares yet.</div>}{items.map(share=><div key={share.id} className="mb-2 rounded border border-[var(--ui-border)] p-2"><div className="flex items-center justify-between"><span>{share.title} · {share.visibility}{share.revoked?' · revoked':''}</span><div className="flex gap-1"><Button className="h-6" variant="outline" onClick={()=>void window.electronAPI.openExternalUrl(`${serviceUrl}/s/${share.slug}`)}>Open</Button><Button className="h-6" variant="outline" onClick={()=>void loadComments(share)}>Comments</Button><Button className="h-6" variant="outline" onClick={()=>void patch(share,{revoked:!share.revoked})}>{share.revoked?'Restore':'Revoke'}</Button></div></div><div className="mt-2 flex gap-2"><select value={share.visibility} onChange={event=>void patch(share,{visibility:event.target.value})} className="h-7 rounded bg-[var(--ui-control)] px-2"><option>public</option><option>unlisted</option><option>private</option></select><input type="datetime-local" aria-label="Share expiry" onChange={event=>event.target.value&&void patch(share,{expiresAt:new Date(event.target.value).toISOString()})} className="h-7 rounded bg-[var(--ui-control)] px-2"/><Button className="h-7" variant="outline" onClick={()=>void patch(share,{expiresAt:null})}>No expiry</Button></div></div>)}{selected&&<div className="mt-4 border-t border-[var(--ui-border)] pt-3"><strong>Comments · {selected.title}</strong>{comments.map(comment=><div key={comment.id} className="mt-2 flex items-start justify-between rounded bg-[var(--ui-control)] p-2"><span>{comment.author_name} at {Math.round(comment.timestamp_ms/1000)}s: {comment.body}{comment.resolved?' · resolved':''}</span><div className="flex gap-1"><button className="text-[#0D99FF]" onClick={async()=>{await window.electronAPI.shareApi(serviceUrl,'PATCH',`/v1/shares/${selected.slug}/comments/${comment.id}`,{resolved:!comment.resolved});await loadComments(selected);}}>Resolve</button><button className="text-red-500" onClick={async()=>{await window.electronAPI.shareApi(serviceUrl,'DELETE',`/v1/shares/${selected.slug}/comments/${comment.id}`);await loadComments(selected);}}>Delete</button></div></div>)}</div>}</div></div>;
}
