import { useCallback, useEffect, useState } from 'react';
import { Button } from '../ui/button';
import {ShareHistoryDialog} from './ShareHistoryDialog';

type Session = { state: 'loading' | 'signed-out' | 'signed-in' | 'expired' | 'offline'; user?: { displayName?: string; email?: string; avatarUrl?: string }; message?: string };
export function TopooUserPill() {
  const [session, setSession] = useState<Session>({ state: 'loading' }); const [open, setOpen] = useState(false);const[history,setHistory]=useState(false);
  const refresh = useCallback(async () => setSession(await window.electronAPI.topooSession()), []);
  useEffect(() => { void refresh(); return window.electronAPI.onTopooSessionChanged(refresh); }, [refresh]);
  const name = session.user?.displayName ?? session.user?.email ?? 'Topoo user'; const initials = name.split(/\s+/).map(value=>value[0]).join('').slice(0,2).toUpperCase();
  if (session.state !== 'signed-in') return <Button variant="outline" title={session.state === 'offline' ? 'Topoo is offline. Local editing and export remain available.' : session.state} onClick={async()=>{setSession({state:'loading'});try{const next=await window.electronAPI.topooSignIn();setSession(next);}catch(error){setSession({state:'offline',message:String(error)});}}} className="h-[26px] text-[10px]">{session.state === 'loading' ? 'Topoo…' : session.state === 'offline' ? 'Topoo offline' : session.state === 'expired' ? 'Session expired' : 'Sign in'}</Button>;
  return <div className="relative"><button onClick={()=>setOpen(value=>!value)} className="flex h-[28px] items-center gap-2 rounded-full border border-[var(--ui-border)] px-2 text-[10px]">{session.user?.avatarUrl ? <img src={session.user.avatarUrl} alt="" className="h-5 w-5 rounded-full"/> : <span className="grid h-5 w-5 place-items-center rounded-full bg-[#0D99FF] text-[8px] text-white">{initials}</span>}<span className="max-w-24 truncate">{name}</span></button>{open&&<div className="absolute right-0 top-8 z-[100] w-40 rounded border border-[var(--ui-border)] bg-[var(--ui-inspector-surface)] p-1 shadow-xl"><button className="w-full rounded px-2 py-1.5 text-left text-[10px] hover:bg-[var(--ui-control-hover)]" onClick={()=>{setHistory(true);setOpen(false);}}>Share history</button><button className="w-full rounded px-2 py-1.5 text-left text-[10px] hover:bg-[var(--ui-control-hover)]" onClick={()=>void refresh()}>Refresh account</button><button className="w-full rounded px-2 py-1.5 text-left text-[10px] hover:bg-[var(--ui-control-hover)]" onClick={async()=>{await window.electronAPI.topooSignOut();setOpen(false);await refresh();}}>Sign out</button></div>}{history&&<ShareHistoryDialog onClose={()=>setHistory(false)}/>}</div>;
}
