import {
  createProjectFromLegacyEditorState,
  validateVideoEditorProject,
  type LegacyEditorProjectInput,
  type VideoEditorProject,
} from "../src/components/video-editor/project";

const input: LegacyEditorProjectInput = {
  projectId: "project-track-hierarchy",
  projectName: "Track Hierarchy Smoke",
  videoPath: "/tmp/toscreen-track-hierarchy-proxy.mp4",
  originalVideoPath: "/tmp/toscreen-track-hierarchy.mov",
  companionAudioPath: null,
  durationSeconds: 8,
  projectDurationSeconds: 8,
  zoomRegions: [
    { id: "zoom-parent-1", startMs: 1000, endMs: 4200, depth: 2, focus: { cx: 0.4, cy: 0.4 } },
    { id: "zoom-child-1", startMs: 2600, endMs: 6200, depth: 4, focus: { cx: 0.7, cy: 0.58 } },
  ],
  trimRegions: [],
  annotationRegions: [],
  audioRegions: [],
  cursorData: [],
  cursorSize: 1.5,
  cursorSmoothing: true,
  showVectorCursor: true,
  cursorOffset: 0,
  cropRegion: { x: 0, y: 0, width: 1, height: 1 },
  wallpaper: "/wallpapers/wallpaper1.jpg",
  shadowIntensity: 0.5,
  showBlur: false,
  motionBlurEnabled: true,
  borderRadius: 20,
  padding: 60,
  aspectRatio: "16:9",
  exportQuality: "good",
  now: new Date("2026-06-30T00:00:00.000Z"),
};

const validProject = createProjectFromLegacyEditorState(input);
const validResult = validateVideoEditorProject(validProject);

if (!validResult.valid) {
  fail("Expected valid track hierarchy generated by legacy adapter.", validResult);
}

const childTracks = validProject.tracks.filter((track) => track.parentId);
if (childTracks.length !== 1 || childTracks[0].parentId !== "track-camera-main") {
  fail("Expected one generated camera child lane.", {
    childTracks,
  });
}

const missingParentProject = cloneProject(validProject);
missingParentProject.tracks = missingParentProject.tracks.map((track) => (
  track.parentId ? { ...track, parentId: "track-missing-parent" } : track
));
assertInvalidWith(missingParentProject, "references missing parent track");

const selfParentProject = cloneProject(validProject);
selfParentProject.tracks = selfParentProject.tracks.map((track) => (
  track.parentId ? { ...track, parentId: track.id } : track
));
assertInvalidWith(selfParentProject, "cannot use itself as parent");

const mismatchedParentProject = cloneProject(validProject);
mismatchedParentProject.tracks = mismatchedParentProject.tracks.map((track) => (
  track.parentId ? { ...track, parentId: "track-video-main" } : track
));
assertInvalidWith(mismatchedParentProject, "must match parent track");

console.log(JSON.stringify({
  status: "ok",
  tracks: validProject.tracks.length,
  childTracks: childTracks.map((track) => ({
    id: track.id,
    type: track.type,
    parentId: track.parentId,
  })),
  warnings: validResult.warnings,
}, null, 2));

function assertInvalidWith(project: VideoEditorProject, expectedErrorText: string) {
  const result = validateVideoEditorProject(project);
  if (result.valid || !result.errors.some((error) => error.includes(expectedErrorText))) {
    fail(`Expected validation error containing "${expectedErrorText}".`, result);
  }
}

function cloneProject(project: VideoEditorProject): VideoEditorProject {
  return JSON.parse(JSON.stringify(project)) as VideoEditorProject;
}

function fail(message: string, details?: unknown): never {
  console.error(JSON.stringify({
    status: "failed",
    message,
    details,
  }, null, 2));
  process.exit(1);
}
